### ISSUE TITLE
%albumartist% issue

### ISSUE THREAD

**Issue by bendwyer** [thebigmunch/gmusicapi-wrapper#11]
I'm trying to download my music to a specific path, using the patterns on [this](https://thebigmunch.github.io/gmusicapi-scripts/usage/#output-pattern-replacements) page.

My code is as follows:
`gmdownload "/mnt/%albumartist%/%album%/%track2%. %title%"`

The problem is that the output (and resulting folders) include %albumartist% instead of the actual album artist data.

```
Downloading ### song(s) from Google Music

(  #/###) Successfully downloaded -- /mnt/%albumartist%/Guardians Of The Galaxy (Awesome Mix Vol. 1)/06. I'm Not in Love.mp3 (36c927de-8dad-3b0a-98e6-039ee042e09c)
(  #/###) Successfully downloaded -- /mnt/%albumartist%/LONG.LIVE.A$AP (Deluxe Version)/01. Long Live A$AP.mp3 (63554390-11eb-3346-86cc-6c9be1e75727)
```

I have also run the same command using `album_artist`, and the results are the same.

I've verified using filters and the Google Play website that these files have an album artist assigned.

**Comment by thebigmunch** [comment]
Ah, looks like mutagen finally added the defacto 'albumartist' for the TPE2 ID3 frame rather than 'performer' we had to use previously. If you want a solution before I get to this, go into gmusicapi_wrapper/constants.py and change ``'performer'`` to ``'albumartist'`` on line 20.
