### ISSUE TITLE
Authentication with G Suite account

### ISSUE THREAD

**Issue by stubar** [thebigmunch/gmusicapi-wrapper#16]
**Please read the contributing guidelines linked above before opening an issue.**
Hi I keep getting ```MusicManagerWrapper authentication failed```. when going through the authentication journey for gmsync.  I am able to use the desktop musicmanager app with this account but I was hoping to use this tool instead.

**Comment by thebigmunch** [comment]
Any issue with that would be handled in [gmusicapi](https://github.com/simon-weber/gmusicapi).
